[package]
name = "rbot-discord"
version = "0.2.0"
authors = ["Raphael <greefine@hotmail.fr>"]

[dependencies]
serenity = "0.6"
serde_json = "1.0"
lazy_static = "1.3.0"
serde_derive = "1.0"
serde = "1.0"
time = "0.1.42"
rand = "0.7"
chrono = "0.4"
log = "0.4"
rifling = "0.4.0"
hyper = "0.12"

# Unused dependencies from commented code
# imap = "0.8.1"
# native-tls = "0.1"
# reqwest = "0.8.6"
