[package]
name = "rbot-discord"
version = "0.1.0"
authors = ["Raphaeël <greefine@hotmail.fr>"]

[dependencies]
serenity = "0.5.9"
imap = "0.8.1"
native-tls = "0.1"
serde_json = "1.0"
lazy_static = "1.0.2"
reqwest = "0.8.6"
serde_derive = "1.0.70"
serde = "1.0.70"
time = "0.1.40"
rand = "0.3"
chrono = "0.4.6"