name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install libmysqlclient-dev libpq-dev
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: greefine/discord-rbot
          tags: latest
